Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Naming/FileName:
  Enabled: false
