version: 2.1

orbs:
  slack: circleci/slack@4.9.3

executors:
  rails_executor:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:<< parameters.ruby_version_tag >>
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images
      - image: circleci/postgres:<< parameters.pg_version_tag >>
        environment:
          - POSTGRES_USER: root
          - POSTGRES_PASSWORD: postgres
          - POSTGRES_DB: doppielitta_test
    parameters:
      ruby_version_tag:
        type: string
        default: '3.0.1'
      pg_version_tag:
        type: string
        default: '13.2'

jobs:
  build:
    executor:
      name: rails_executor
      ruby_version_tag: '2.6.8'
      pg_version_tag: '13.2'
    environment:
      TZ: 'Asia/Tokyo'
    working_directory: ~/working_directory
    steps:
      - checkout
      # TODO: Setup Database, bundle install, bundle exec rubocop, bundle exec rspec
      - restore_cache:
          name: Restore RubyGems Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Prepare the artifact directory
          command: |
            mkdir /tmp/doppielitta
      - run:
          name: Hello, World!
          command: |
            echo 'Hello, World!'
      - run:
          name: Check Ruby version
          command: |
            ruby -v > /tmp/my_artifact
      - run:
          name: Check the installed Ruby path
          command: |
            which ruby > /tmp/doppielitta/which_ruby.txt
      - run:
          name: Install the appropriate version's Bundler
          command: |
            gem install bundler -v 1.17.3
      - run:
          name: Bundle install
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          name: Save RubyGems Cache
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # - run:
      #     name: Execute RuboCop
      #     command: |
      #       bundle exec rubocop
      # - run:
      #     name: Execute RSpec
      #     command: |
      #       mkdir -p /tmp/test_results /tmp/screenshots
      #       bundle exec rspec --format progress \
      #                       --format RspecJunitFormatter \
      #                       --out /tmp/test_results/rspec.xml \
      #                       $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_artifacts:
          path: /tmp/my_artifact
          destination: doppielitta
      - store_artifacts:
          path: /tmp/doppielitta
      - store_test_results:
          path: /tmp/test_results
      # - store_artifacts:
      #     path: /tmp/screenshots
      #     destination: rspec_screenshot
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*'doppielitta' CircleCI done.*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
